# Generated by Django 6.0.7 on 2026-10-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivarity',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
